---
apiVersion: batch/v1
kind: Job
metadata:
  name: prefect-init-db
  annotations:
    kustomize.toolkit.fluxcd.io/force: enabled
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: init-db
          image: ghcr.io/home-operations/postgres-init:18.4
          envFrom:
            - secretRef:
                name: prefect-secret
          resources:
            requests:
              cpu: 10m
            limits:
              memory: 64Mi