apiVersion: v1
kind: Secret
metadata:
  name: staging-init-db-secret
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:5vEBPSRx,iv:ZrWvapcmv5oCaq2iVi+w2qqL/814FcIYRoNq2E0KgII=,tag:fY5l6jC90a5pDTAsz/athw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:GGZJ8txe,iv:kb/WZpupl1LQI0Gn9toA5P2DsP5M2FzMcyvqdScaXgI=,tag:PWqeafVTjuDCqO+3vuPWew==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:14n77uMm,iv:MGJYYCNXZfyZeWW2h9laUseTJlhRqJsVWg5Jj12QtAw=,tag:AEPufM3l47voUxMcUK62Ug==,type:str]
sops:
  age:
    - recipient: age19r6wen3fypsw5ykk0dj2e2hc0tyw2zlux6mw33c57pfg5jd9mg9sgjp3za
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzQkNJS3VQQVZSOVdOWGdY
        bWdUYVBTSUdENzB2RjcvM2lQSGNzQXJFcW53Cm9Ud2xqZngxR3QxYmYxYUFPRkwy
        enI2aWJDYzhIOCszWm9XU0RjT0VxRlkKLS0tIFZjbjR0dllQUTYvckpZMTZSRUlI
        bTZFajNDRjVzVnlCeGlqMUgrQTA2amsKuKchHPMHuDHz0TK0Ywp9olOX+VbH71aI
        4LcZhUibqHAlUN67N1ixJp9ObhMb41qvf6yoTODvSQcfLkQ5aWaM+w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T21:44:09Z"
  mac: ENC[AES256_GCM,data:i8gJWZHLdgIGuxUEUa7e/dplZnreg/PfLX/p3s17bfiUV8qTC2kwH/7iDRxIuh88bRfwhmNWhTuUPcJ6irc8cxAMS6b3BwV2NBpvrTOJxGzr9ljSui98b+VyK3k4hUnHwzsTjPHnszrD2oadyPM7dpBMiHPhRpSOFjBUmaXdKFg=,iv:O3RN5Vo5+OSOZk/gimYMxACtq3ooZTv0eOe/Tgjpqto=,tag:Zr5l1TG334J/oFaHZ36wyg==,type:str]
  pgp:
    - created_at: "2026-03-28T21:44:09Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DAq0yvRRAWQ0SAQdAImCN49XgdFDi+aMZa/fTt4UnDkReo77x4vpM84KZRw0w
        LN7+htsHF0eQnYY3XfC6MNvCByMUH4fiiNGGzFe5wKHJd5egkl46vUt/NI5QN/+9
        0l4Bf077wPjXtt/RVOjoXwwHYYDIxTmCXMFFZH3HLm0wCTMtc3+1HPKcMUuw+GVE
        QYGsLRPpI01FI8ab6mTGwnOOtYp1Qci8v9+efGjWC9tFs811vzUBpgDcWN2fxiJ1
        =ebZX
        -----END PGP MESSAGE-----
      fp: 1818334CEAC35348ED5E30F5DD40CEDB2EEAD4A4
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
