# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:E4TSmT6ln7CRWDW1mfj89vl5WKwGedPRFt1n99wZFQBAwLdrEQCS/g==,iv:qAXvY3o6N+c7yOXgQYKFnar7Atx389PgNQjZyesLQFg=,tag:2cbpLje/+8R1Zq4nSUjbsQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19r6wen3fypsw5ykk0dj2e2hc0tyw2zlux6mw33c57pfg5jd9mg9sgjp3za
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGWm9EZjJyYWFHZnlWTFVL
        NmNJOUhPL1YrSVVMa3ovZmVwSjVuTzlxTTJZCkhaaC9EQzczaHJuamhmQkVXaGJa
        bWtIN2d4SHhZSmRVMXhHQlRqcDhtVjQKLS0tIEM3bnlCZ3dEUnptb2FONDJ4LzRH
        MGRWcUgxNWhHTkJEVGk1UFhjMmtTcmcK2j7o5dlglqac2+6OtNTrztAq6TREFNcF
        Ux+8Hl5DYMWV120eIlvs1ZL+WKMqLYTyI99956hHYu9z8Fat+PYJIA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-23T05:41:35Z"
  mac: ENC[AES256_GCM,data:2vJawPV3BWpXuKezzioh285GPYV4CIItRehaFRlgZ63Lq7KHG9ALbcxx1sEsEQ5ifl3ZyNfYWH9h6dtkXWYJKjGBu7Mz6nTU05t9gkLiKEsT6kxMJYH/I9Lfgj8gwFRiYL5sidRsX/sbHd/sS/u1rN9pAjKiXb1R9mfNGH7xs2Y=,iv:WhMfHu6NJzc+9q6COthssQD64EOg9jfmcEWDzqXM0zc=,tag:0Bqx0BDkrfOee6VSvXAWtw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
