---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actual
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      actual:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/actualbudget/actual-server
              tag: 25.5.0
            env:
              ACTUAL_PORT: &httpPort 80
              ACTUAL_OPENID_DISCOVERY_URL: https://auth.${SECRET_DOMAIN}/.well-known/openid-configuration
              ACTUAL_OPENID_SERVER_HOSTNAME: https://actual.${SECRET_DOMAIN}
            envFrom: &envFrom
              - secretRef:
                  name: actual-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *httpPort
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 12m
                memory: 128M
              limits:
                cpu: 100m
                memory: 512M
    service:
      app:
        controller: actual
        ports:
          http:
            port: *httpPort
    ingress:
      app:
        className: internal
        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: actual
        globalMounts:
          - path: /data
