apiVersion: v1
kind: Secret
metadata:
  name: sandbox-init-db-secret
stringData:
  #ENC[AES256_GCM,data:wqCZz+LMpf3saF2bAtsMC87DFpb8dLE5qlN7MtzplW4b7OXBgoFPdMS1+CI=,iv:N2IhkeVR4m/Ok2r8h/7UBHJUTczmVTi3PMh5dRLzRvs=,tag:t0TBtvEnRDr5a7jredAiJQ==,type:comment]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:5a/G6SdjuvnESBYqxb0=,iv:aqXsfSLbfz+7BqKMJmsThW8wpQkz0C3Pf6T5Zvt9F44=,tag:3yqmNTlrI5PVZQLS9NYNmw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:mLrMAJ25UQ==,iv:3+BHHAgeqLMMSpx2lxr9raqfvWMkJBOyc+XI/Qqypew=,tag:gNuISseC1JBFXiZo5kqHrw==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:6IageRwI2g==,iv:LH5B9xyQIbQR12/LE+xk9u7NkCazryX8Fqh5hvj3I+M=,tag:UXHSq9PBj1vUCI4Rb1b8VA==,type:str]
sops:
  age:
    - recipient: age19r6wen3fypsw5ykk0dj2e2hc0tyw2zlux6mw33c57pfg5jd9mg9sgjp3za
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TFdlMjFKRlU1SHpMcGN6
        Tkc2dHhUaldhN0Y5aXVnVThBQVo2U2dpeW5JCjdsZmd1cEJnbXBNLzRqQ2Vaeng3
        dm0vaXhIRlhpYW1KTFVDWi8rQ2ZPUWMKLS0tIGRHNlN0RnpGUXNkWEpDVnpmR0Zr
        UlRveW1CTDhFT05iazYyckh6aWxveTQKCvGrHy28TJcq1EA5VaiA/Ne7r9GAJf0A
        DnLxHiFeA+wTscAY/N48nVyyk3IXMAJXEHurbplRiOxg+RRomGbR7Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-22T13:29:34Z"
  mac: ENC[AES256_GCM,data:XqYoc/Yjxc+GgziJ9jRAxwbmaQI1OZ7PqqB/4cwspKRLsBlWprfu2tBytf20+5OeEyIL+UBEic6cUp8aJLERf1AbgdITEO3NhbhdhD5SGYdeh1kM1YYEdlHaCoZcupWagmh6Mk6ka4Owhr3ErWuUHNyE/EmTxtU3YfFIJaPvyNQ=,iv:K21o3Ll4zv5OPCaL3VuuqqRE2d6VVfiJ8wObA4g7ypE=,tag:mDWstyuS8gHAFGUON/LaEQ==,type:str]
  pgp:
    - created_at: "2026-03-22T13:29:34Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DAq0yvRRAWQ0SAQdAM61S36hdm/Q3e7ayqfWccEUgfze6CXLXFgT/uE0eIXUw
        ruI198nZmuo6/3lPesAsDdfrZ4r/stjCmbikddOZ4JuOTzitQhNPrLHtaapE8m2r
        0l4BbbNqy0Kbjq29E9zsnHW03YrtBU3MIEXojZCQlslCKwMHfps3aa+RjxjdfK6H
        2RhmU1D9cX/mFogI7rn+KFbHE0VUc9yRZBsqc6RJOIN+Drq7Y7ApE5LoEOXp/yh6
        =Q14E
        -----END PGP MESSAGE-----
      fp: 1818334CEAC35348ED5E30F5DD40CEDB2EEAD4A4
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
