---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudnative-pg
components:
  - ../../components/common
  - ../../components/repos/app-template
resources:
  - ./cloudnative-pg/ks.yaml
