---
# yaml-language-server: https://raw.githubusercontent.com/marcolongol/CRDs-catalog/refs/heads/main/external-secrets.io/clustersecretstore_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepassword:
      connectHost: https://onepassword-connect.${SECRET_DOMAIN}
      vaults:
        homelab: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: op-credentials
            key: token
            namespace: external-secrets
