# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:K0BtIi8IhsRgfaFA3iRhiZ5nS+POMCGXlthn87wZB1bQC2PphZSH6w==,iv:R8DCYuzqGmbbA5THAG0qQ+Ly1ggMNHoCYbo457Jaags=,tag:fEMfDByPEEjCvJ71jI5F2g==,type:str]
sops:
  age:
    - recipient: age19r6wen3fypsw5ykk0dj2e2hc0tyw2zlux6mw33c57pfg5jd9mg9sgjp3za
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZlZ2YkNvZWtZVFF2NXB6
        aTB3UDg4TzVISjh2Y2FibmVBdHVSZS8yZjFBClNPUGkySXBjLy9pZlpBSGN3anFk
        OFFSSjZXTkVzOHYreXBOZEpBeFAzODQKLS0tIG9LY25QN3h0SkR6STMrUG1ENndN
        clptUng3S0h1RENkYS9MVGxNQTBNVjAKh525v24/7MoneepyA842aOU9R76tUVIh
        w3nXoOBmyflBYkcNhQ1AIkn5bTMi36QOfioqrpPmtWP/9OfINb0n7g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-23T05:41:35Z"
  mac: ENC[AES256_GCM,data:QI1FMqLSO6myfMsl7nZ2CkZ33xwNWRLRpsVp0Wf85kbamQOpZdNIPhIVqZZDsUiFBldW+CCtqgRth8zD7q0jNi9CXehGrXCreXyqP5tS57l3xU2d4r2YLCJpdgkomUOqcwq68pHcCU5KoSYZfzVCImyDE44NtNCeTG8+bP6G5/Y=,iv:+qXwqElJN0aiQymBbxzWU0S35868cR0vzGohHHFJTJ4=,tag:fxJqVqH1IPOTw8Awn8LsAA==,type:str]
  pgp:
    - created_at: "2026-03-22T11:27:42Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DAq0yvRRAWQ0SAQdATuX3Ey9F2fUzA97eyqHjH8w4QcMCuVVGB+KFs/bETBww
        MyzAVzpSTa72zmafHOcM3Xap2Cw0cDmIvdB6OGDb+z46+efw9TZMcjNz1rgvFJAf
        0l4BFeKYQNhwjaFyyNKkoVvleUXOTaQ5wxFJm6fBUmn3s+xQUjN5WjalN2Vq7F3r
        qirvCq4cFqVf/2bm8EpScdeskRfO3fO7bA1sdLiOlZvNqpsCNw/TWYWtL6iQ07rI
        =1Cpm
        -----END PGP MESSAGE-----
      fp: 1818334CEAC35348ED5E30F5DD40CEDB2EEAD4A4
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
