apiVersion: v1
kind: Secret
metadata:
  name: dev-init-db-secret
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:udrx+n4J,iv:SdF5/BhPMX/TrRLmkaUpLaYbdlYBbTwkYXFGZH/cq24=,tag:mLqZp3TgZkvRI/cqQ6VOSg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:NQ9J8VkM,iv:bedVKDty1Y8SASCDkDpdwTK1N8Nb5fEGOqHxmRF4uTM=,tag:kJW3KywLfC62OG53T8+8uA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:6s4Q5FvM,iv:6yxkwA4u36QzUO/Ny83WabYvJ7aJobGmGst7VbUtF24=,tag:QAw/HN6AJHJ4dwJzGUqPyA==,type:str]
sops:
  age:
    - recipient: age19r6wen3fypsw5ykk0dj2e2hc0tyw2zlux6mw33c57pfg5jd9mg9sgjp3za
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwV2ZJVXlHSkhGRjY4UFdY
        TXFGTzNJUHlsMXI3M2JSYmRYejFITk9ZUVNnCjN1RG5SSEhCdm8ySUNWQnZhRm9j
        L0c1RWFQekVlK0ZiNzlJaWorc3pWVzgKLS0tIElrelBvL3QySmhzakJZWE5aYTZC
        UEpjeFI2YXRDaFZML2k4UFFYT2ZldncK7SlQ/ZIIsU34oXQBPfZ/+OEVrLRyvAyj
        8uobidCecdxuOf3otG52eBPInPpgfrsJwBJJu/tOQgqXHZG+Q3mAwA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T21:44:09Z"
  mac: ENC[AES256_GCM,data:mz+45PtEfk62J6iI8snU3XMYaOqNl5LZ0CUkLAgjY7baOHmcozm9aQoYdiL2PF1EPyaOE3jduwS1O+cOEdXkEqNC4N0Wh8CnXfczB7MDQkF6Pi3AlYiK8zaDZW8nLb+h44XEL3jD2pdiV0UivL2TklShNVsxEjZEkgbpMr0BVYs=,iv:EqDzAUALkTdQO/b7YOvK7EGtcx+JskWie2bb7dIx7Q0=,tag:NVt0MF2NV/20YBxQvqwMIA==,type:str]
  pgp:
    - created_at: "2026-03-28T21:44:09Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DAq0yvRRAWQ0SAQdA5QxZ0HI4lg9yvOdQ5+bg5MELm9nHdEqj9Ou4oPBNWn4w
        cRZ1U+RCroIG8fq6LNU+JZWIL0QfVZZBOVojV/lzbMD6SUUElvWtxbO95KF5Mt2r
        0l4Bo1YX4j1TbrkmdagyNIOCuMf5CBIR+rumzbUmYQhkCP+wl338XfPlTJzHyDQ6
        vticNlvsZMBLlrerZ9h+7MaRUjN8sXAWdqwGIV3IkMBCKK8zfQQBgVugehO7Begb
        =3fdu
        -----END PGP MESSAGE-----
      fp: 1818334CEAC35348ED5E30F5DD40CEDB2EEAD4A4
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
