# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:iC87Q3t7tszO8Aj6h6oBq/W0eiuXNi3YCj+kkoIzozQ=,iv:mUpBlu2ObFhY3zyL3qipY0RVh5RXPqdIamGOhEbMk7Y=,tag:m0VEaVDg1lVMLG1bSum1kA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19r6wen3fypsw5ykk0dj2e2hc0tyw2zlux6mw33c57pfg5jd9mg9sgjp3za
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZGlYazFVaDl2bXFZWGE2
        NGVsZ0J4ZDJ1ZTc4SUZBRXBYbm5YYUZNbDFjCko3OWRUSmpiNlM4ZzJPS21YcFRP
        bitLdkZUcGN5SnJ3dDBKVWhOU2d6R1kKLS0tIFNkeGhYWHUxdkNWWnRtZ1dtY1kv
        dkZiNDBXTDRwZk9RR0xTengxdlJKRm8KFfc8Q7ksd2wUUxPY/8JG3bX0RY0Dz61t
        dTom+FVsc1QQbL+nBV89WBIVJpOdUe3XpNXEXuFq/0RP3LW4opbiMQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-23T05:41:35Z"
  mac: ENC[AES256_GCM,data:THntoqI/iCOEobHqj772j+VUqU/QKf4dnhF6s2yywg/XdaOXrbmgw//eioBOj3YaW63sK6wze4R2eE/CFn5jbY4v3vEgiBmHrmaNNvSVwB6ib/wj7c7iWi9yccgcYF+y5x4AzR0LhkB0sn8Bi4ava+akj4gHTCkTPpSeoCBud5U=,iv:k2jqj9kn5wRGlc9+ba9Hd8UP/FOgOEyUogIl+n5QbKY=,tag:Zc6K3SGAXfKb4QN7UGXe9g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
