kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
metadata:
  name: openebs-snapshot
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
driver: io.openebs.csi-mayastor
parameters:
  "protocol": "nvmf"
  "repl": "1"
  "fsType": "xfs"
  "thin": "true"
deletionPolicy: Delete
