# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:dhn1GI7jCh+qWu003ccy6hvodRegGb0r4XdtYhc1hwXy+uGuP25ofo1NDvYJXrrTVX7ePNp+CNiNY+asbwmh2JdQBrEZA9jKiSIdGMxGR5COtk+aaLKbNErFQ6jO3dfoRIb9LQBUjSrfZCtSFB6htd5I/uqNzMnMgWOZQBqWBxmMWPJxy3lLKJMjpl56fUELdPIT5PV/pcpEW3AKJDYanlxTOBU21VRLBG18udsPX/3eQ2oYFA==,iv:LpJrnFu1zWHbnyraBWPWSIwU8Ch9+KSi9hfKH9H7LDQ=,tag:BGWwbZN9OUtO+v6pwE0fMQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19r6wen3fypsw5ykk0dj2e2hc0tyw2zlux6mw33c57pfg5jd9mg9sgjp3za
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlOXpGYTlOcGpFUFUyWnk5
        MS9DSFh6TXRDWEl1Zi9yYXpnUDcvNUgyQ0FRCjBRMUJmSlhqOUd4cWp6MkUxb0Fs
        ZmFHRVpaMmhwam5hZk5Cb01wTU1oMmcKLS0tIGxYcms0ZXZKWVNwOG16TGV1WVdl
        cmVLU3d2Nnc4NG93MXZDNWYrc0pWUm8Kaf/izcPAWa8V9lZRVjQ5NDTzY7Hx8Bc1
        6Mjd/LuZqrK3GwEIJ0P01FyGU9YdwP+C54i93dz9o+qjTwTkdOX6+A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-23T05:41:35Z"
  mac: ENC[AES256_GCM,data:fUkyUU8uJp26LDaLZxPMcvu7AWSxSqO0VVwBYlua2xDQPxqKqUlnOwZlIsLrItCtoucNYmYQ4GPfAgikbXbCK2KSdOlH20dxdZ084y0zv5L/bO2BzA3gy/zbattSIP8p4kiuntYZViI4zg9f/pBJysCJcdarzdIQNEdIa1mRfcY=,iv:MhYeKq8jN+dpU5HLtTpdg1JWPKbXLj00xTQ9Cv5T9qM=,tag:X3GH9aiNVVdVXy1E9T3loA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
