# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:dhn1GI7jCh+qWu003ccy6hvodRegGb0r4XdtYhc1hwXy+uGuP25ofo1NDvYJXrrTVX7ePNp+CNiNY+asbwmh2JdQBrEZA9jKiSIdGMxGR5COtk+aaLKbNErFQ6jO3dfoRIb9LQBUjSrfZCtSFB6htd5I/uqNzMnMgWOZQBqWBxmMWPJxy3lLKJMjpl56fUELdPIT5PV/pcpEW3AKJDYanlxTOBU21VRLBG18udsPX/3eQ2oYFA==,iv:LpJrnFu1zWHbnyraBWPWSIwU8Ch9+KSi9hfKH9H7LDQ=,tag:BGWwbZN9OUtO+v6pwE0fMQ==,type:str]
sops:
  age:
    - recipient: age19r6wen3fypsw5ykk0dj2e2hc0tyw2zlux6mw33c57pfg5jd9mg9sgjp3za
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbDg5ZU9laDIrMzMrRWJi
        UDNzM2pkeGFxdmFHVE5Jcm1pZXFsNVVhcUNRCnhPVkNXUTRDc3k0N2ZBR2NXUmFp
        UFZSa2VKY0kzMmVMMmV4ck9oM3pXM3MKLS0tIHNvS2t2Z3pOc0l4eDRxZVBvaHNY
        ZXpkRmRIdjNDdkRPTkw2MktYd3hyRkUKyEA3H6YUm6WQQddPwlbcw5dW88VMCdrc
        zjXixxCj+6VZq3jsUKac24pOcpitv5+dXML8rFKwkQviIjpwaL1E9A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-23T05:41:35Z"
  mac: ENC[AES256_GCM,data:fUkyUU8uJp26LDaLZxPMcvu7AWSxSqO0VVwBYlua2xDQPxqKqUlnOwZlIsLrItCtoucNYmYQ4GPfAgikbXbCK2KSdOlH20dxdZ084y0zv5L/bO2BzA3gy/zbattSIP8p4kiuntYZViI4zg9f/pBJysCJcdarzdIQNEdIa1mRfcY=,iv:MhYeKq8jN+dpU5HLtTpdg1JWPKbXLj00xTQ9Cv5T9qM=,tag:X3GH9aiNVVdVXy1E9T3loA==,type:str]
  pgp:
    - created_at: "2026-03-22T11:27:42Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DAq0yvRRAWQ0SAQdAdQce9iTD1m4HERxYSwHRGrZPPZ212r458ty91h+1ix4w
        zM6gnIM6XKf2UYcfneqdLOKjmcx1AXIqXmJdblOXk3XjzD7gkYRcKPpk3mq/Nve6
        0l4BMiuGcyJ8MqzBMFaMl+l7CwDLT9DZiwI5V3c+kf+LEtG+1chxqywk8p6cxYU7
        uf7RQbkqxhUWK94EvKsdCZI9O9VxDD3R5n0A4WA0D/k2FXdyqKgH6hyk0bkTRtkP
        =TK+D
        -----END PGP MESSAGE-----
      fp: 1818334CEAC35348ED5E30F5DD40CEDB2EEAD4A4
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
