---
# yaml-language-server: $schema=https://raw.githubusercontent.com/marcolongol/CRDs-catalog/refs/heads/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minecraft-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: minecraft-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RCON_PASSWORD: |-
          {{ .RCON_PASSWORD }}
        CF_API_KEY: |-
          {{ .CF_API_KEY }}
  dataFrom:
    - extract:
        key: MINECRAFT
