---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/service-v1.json
apiVersion: v1
kind: Service
metadata:
  name: firewall
spec:
  type: ExternalName
  externalName: ${CONFIG_OPNSENSE_IP_ADDRESS}
  ports:
    - name: http
      protocol: TCP
      port: 3000
