---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cnpg-grafana
  namespace: flux-system
spec:
  interval: 2h
  url: https://cloudnative-pg.github.io/grafana-dashboards
