---
# yaml-language-server: $schema=https://raw.githubusercontent.com/marcolongol/CRDs-catalog/refs/heads/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-init-secret
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: gitea-init-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        INIT_POSTGRES_HOST: cloudnative-pg-rw.cloudnative-pg.svc.cluster.local
        INIT_POSTGRES_DBNAME: gitea
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASSWORD }}"
  data:
    - secretKey: POSTGRES_SUPER_PASSWORD
      remoteRef:
        key: CLOUDNATIVE_PG
        property: POSTGRES_PASSWORD
  dataFrom:
    - extract:
        key: GITEA
