---
# yaml-language-server: $schema=https://raw.githubusercontent.com/marcolongol/CRDs-catalog/refs/heads/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: authelia-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # SECTION: AUTHELIA CONFIG
        AUTHELIA_AUTHENTICATION_BACKEND_LDAP_BASE_DN: "{{ .LDAP_BASE_DN }}"
        AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: "{{ .LDAP_PASSWORD }}"
        AUTHELIA_AUTHENTICATION_BACKEND_LDAP_USER: "{{ .LDAP_USER }}"
        AUTHELIA_DUO_API_HOSTNAME: "{{ .DUO_API_HOSTNAME }}"
        AUTHELIA_DUO_API_INTEGRATION_KEY: "{{ .DUO_API_INTEGRATION_KEY }}"
        AUTHELIA_DUO_API_SECRET_KEY: "{{ .DUO_API_SECRET_KEY }}"
        AUTHELIA_JWT_SECRET: "{{ .JWT_SECRET }}"
        AUTHELIA_STORAGE_ENCRYPTION_KEY: "{{ .STORAGE_ENCRYPTION_KEY }}"
        AUTHELIA_STORAGE_POSTGRES_ADDRESS: &dbHost cloudnative-pg-rw.cloudnative-pg.svc.cluster.local
        AUTHELIA_STORAGE_POSTGRES_DATABASE: &dbName authelia
        AUTHELIA_STORAGE_POSTGRES_PASSWORD: &dbPass "{{ .POSTGRES_PASSWORD }}"
        AUTHELIA_STORAGE_POSTGRES_USERNAME: &dbUser "{{ .POSTGRES_USER }}"
        # SECTION: POSTGRES
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASSWORD }}"
        INIT_POSTGRES_USER: *dbUser
        # SECTION: OIDC
        OIDC_JWKS_KEY: "{{ .OIDC_JWKS_KEY }}"
        ACTUAL_OIDC_CLIENT_ID: "{{ .ACTUAL_OIDC_CLIENT_ID }}"
        ACTUAL_OIDC_CLIENT_HASHED_SECRET: "{{ .ACTUAL_OIDC_CLIENT_HASHED_SECRET }}"
        PAPERLESS_OIDC_CLIENT_ID: "{{ .PAPERLESS_OIDC_CLIENT_ID }}"
        PAPERLESS_OIDC_CLIENT_HASHED_SECRET: "{{ .PAPERLESS_OIDC_CLIENT_HASHED_SECRET }}"
  data:
    - secretKey: POSTGRES_SUPER_PASSWORD
      remoteRef:
        key: CLOUDNATIVE_PG
        property: POSTGRES_PASSWORD
  dataFrom:
    - extract:
        key: AUTHELIA
