---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: grafana-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        admin-user: admin
        GRAFANA_OIDC_CLIENT_ID: "{{ .GRAFANA_OIDC_CLIENT_ID }}"
        GRAFANA_OIDC_CLIENT_SECRET: "{{ .GRAFANA_OIDC_CLIENT_SECRET }}"
        GF_SECURITY_ADMIN_PASSWORD: "{{ .GRAFANA_ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: AUTHELIA
    - extract:
        key: GRAFANA
