apiVersion: v1
kind: Secret
metadata:
  name: op-credentials
stringData:
  token: ENC[AES256_GCM,data:gSezV/uoYDP+/HI5wEumWXqjF1DEY16B4KeYZ+CJ4sa/d/gRi72KmnS4SXX4l1daJggYjNbf+21EmwDyX1h1HmIHQgL2e4/kyNpfr/8s1mO3lOkXW9+B0bGErGdVWExF186EhyPpNS3pf4mZbttBimPpZyFQ7PWTaVH7RjO7V8oUqOpCZ1wCaTDv8gjQnDSxiHZgiprPXAwTREtAJ0waTjvesPwce34W9W6mXyb3a5CzaKUac7aT3lHukuT6T7vyKlbW/uArQsbs/DYl6HT96SC9fy1i8K+WlDZY/AFwYkeRuRLBw+jN3A1b6iIu95Rwxwywg/npiJOic9y6B7zNA3GYbkFmGQyxuKV708Wl1Wr6GUS5RMUdEkuXIXhsN7MQt9aaDEeIGMpJGC1DeCE7oGqVOToeuHRha0W8esa3T+FWQ4tuWY0l4ZxUIqKx1UMVU3ItRUcPX22v/4kGO02a/5r2i5LCC8SjaUhawQhDI81qx6fyXRTgRkT1xIdv7zqu0ZjCnlmVPuOStdbHJIEIMm2iQIgmmYXnPfeg6JMo53eLKmfbDolPQPKlWY4TrgPw1Txo/YU9j+7748uIDBDEkc4/58HX97YQYE8jIgGRRoeGzH2ZZn1JmWpvXofgh9OFtQ9l0yWsJq6oInWO3RYSfgbyWt6/i+Z/e23HuBbEDL7l/aLFp46P+FU17TT1O7Hpr6xX/V0G4SYTXjDmcYPMVH5zLfa0pPsE59K6wuaTv++6PZOrt+iXRwDZ9fbBm6II8JN6+mMhXhetmGzIgztp2+hMkWnvv9NLTurKp3LZ6M/Aws6ekEW1o5spoAkgTpjpCiQ1QovGIIkTsKhSNpHHyGxn,iv:k9ZLRnjWm4WIU1evt+C9ZpZI2lBZcVtVDRXJHYjGLYk=,tag:z2JKdU9XKVgkGMRiBG58WA==,type:str]
  1password-credentials.json: ENC[AES256_GCM,data:McqqVrJrfqjFt2gaPaz0HY1dK9GqGYffm9TeSI2BM3kUyH77Xzrh+Gt2AAr9tWTfIf1ptUaRheytFBhxUr19lPivf35O/hxoW4keEB0VYZLCdlGdczJcSeCv9Yg/CYX/T/C66c3P5LL361UkQUqXYLP3w0tqOx2kXxEMGeXeg9uRrTDNLQF1o3sFrjGfes8joOfY4yAk1y8dWwDLsnlMbx/6uny7Ze87faT1mFcY6dDQLhqVimP+BY11UzV6/NPWIwdsnz1F0XhAqm1OLtjRstJfEQmj9XutlNwTvE590JC6SEPAdWRX9NfQm3vrPxzAlrtUo1+sHZUaZEab9wPeupLMFeY3VPKOs704dHiJ0OIT+o+d752+Ep9I+c1lGEz8Jhh7t1Y523VyiJGS/7MEXWTD5xTXeDqbt4DyNohhzW6P91MfuVX26MPuMLiSJd8kVDJleOkswl+nAvH/Q0h5YohOhr0ZIpFBh7FKZUBtFUAgyGXjTxCM9K/Ht3B3YWWyW3WIqri1lBWwc6FUp86/YPGaPsucev7YI2abvKTK386gT6g1Ey7y4dQD+JGwP/7FoM0NLBsyWLoEPirFwg35Agn78XDfIFKBL/vdLS2rAhTBRDusRiXmXKwdaQ9i94mj0blUN405IpX9V5beUegx62YCZSgbpiW8Qa0vv+PnpylTS2/l2WyKnMmCmAgrcaTDp0o9x/e1XolKYHGj4J52XtZkltgTWxaRXo4tgLdmmSee1pyuaeGqA22vg9ujggYbLpfL93RScw+mVntiKV6fb3dbzSotrXiEc+imU6iCJMDDrZx5caFxZuhYC1GEJWUdJ4GPBCoKb5M9bz8iht8Qky1n9MXle+T2e7s7Z4EDDVNQuYJ7Nh+dRt8VAUUN85Ji6DIRs6fa8TmZywfXluMsUtDchA7jFNqIhmDX5Qu+ooDKjJ8cHBsaCeIKOjA8v6B2fU2c5lqC2iX8LfdgLiPAsjGM/dQpfUy1sIifArj1LwCYz6M4TnZ2dozOJcZuYd07+8SJkXg7Y5lSlpYlwZ9HY+vEB74AdFPmni/QpMCMPUMQyezO4tzghMPMCX5YnoXKk+S6HILzyU7OTtJkOXF0gurcQue4/DekqrrRioyj+d734cTviX6iHF0wJ6c3N3kLg4+1o0is9Z0YSDefLOt9ivzBxKtp+bPHjGve2HOwa+Qw43ao7zH/0aO1uemScm3fGeO6m23yZ8rEMJACa7PB0HwcchyaEdNUdXhGL7eU5FLl5epNmGfxj284fI8TVdDON6D+cHwhOnWSWruPiUE3BCBnMHQggOJNoweL49yQ/iilKsGHcyNPmDeWhQO2KdyCi9DhiqjfwQYxTEoAlkjknVhFqoaa4dsmGvmW7WER5/tD/d/g+zWR7jSZO5hcCpYHEV1IE/a7+W+BkgDA+UOs7ozAhx+F6iCxp5GTrhhFGw==,iv:YbEf6sxN0mEuLJfE4pxYFBu/hgOLQgQbgLydqdUpMzc=,tag:jUW8eGX2UnVBRX3a9Ev1IA==,type:str]
sops:
  age:
    - recipient: age19r6wen3fypsw5ykk0dj2e2hc0tyw2zlux6mw33c57pfg5jd9mg9sgjp3za
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHeGQzVjRaUEZQSUt3Z0lm
        ai96cGwwbytLb1pkaXg3dU00aTI4TWg0SVZrCkM0TEN6Q2RHMEdkOUMrQmQxMkx1
        NnlXODB2TkJlKzNLdHBhRlZQMFhjMVkKLS0tIG5jT3lhNkE3OXVPZ0lRQkpLN0tR
        K0pwM0s2V0ZBNU1oUFVTY25SdzFCTFkKFrs4nPK/8NB73A1dZGAcae3nmnGIPkmY
        SxwRDEoTsTMiwbYbOzEIR129EcQSH2YlkyarkzJtT0UP4h91n6A4rQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-22T11:37:55Z"
  mac: ENC[AES256_GCM,data:W0ZZ2Loa/6acQA3rL3yBIEr8FJV3Jgp+GctyR4GCu461R3HAS0w/ji4gGk6fzdO/7B0FFaA3sIKjdj3XmrRMGHM1XIdfN8ie4UrK6oqB4YRVbs5oixolkXF535+XY8Mq6dbEv6niTJpve/XAnB4z2cc/GRaqIa0S5FHWMNYR9gY=,iv:46LU0yijzJFr7F0NLs6PeuwY92mNxjvKA3NAQqLCQsE=,tag:Sk1vnAuV8VMg971xouRggw==,type:str]
  pgp:
    - created_at: "2026-03-22T11:37:55Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DAq0yvRRAWQ0SAQdAHahl58qOHPsJa1uRSYzrg7l02IuNooJW+uiNANlstAow
        vd/LqhhD8zKg2fMNf31bldqmQvA0f+pZNuH1bXzlEgi18uXwctrB7I8RsZb9BI08
        0l4BD0WGqSwNwQWgjO3ku+0uRmCr3PmJcS3F8iMugxrB2wabYN1XBTNwdIXX85M9
        uTIvoz/0RXf7zrPSp77jYypdSuNpsmoIroYglhVgtUEGYMGQWWxCmigjtfVVT6wv
        =N4wC
        -----END PGP MESSAGE-----
      fp: 1818334CEAC35348ED5E30F5DD40CEDB2EEAD4A4
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
