apiVersion: v1
kind: Secret
metadata:
  name: op-credentials
stringData:
  token: ENC[AES256_GCM,data:YVTitlrqm35sQhtplpk8rBjluH5H6c91ikH+BJ7OYmXP3ybB/didjY/eyulc0wmwvV7hmY5AomEW8p1YXXe7++y5Yy9XtNiN6u+Pei0VQm+KpbiKFUJA5B6T+CBYAULzaZUL7wtQaAtOUADBf06A7j+cFtq0K41lIgz4TJlh4AX+/4uPe+My2izTTWCmXw1n2e4wXS63Mi1zg0uZUgYfm4G7dyN0B0ppYODNPoikDj7dZ6yvSBHhSIbcLPzX3ifZKCm6+CgbSQOOTGpk9q0zHPGo0OFtSRfgX/UE66QmOel7bMScPEAzcuVemNisMreJgBTEP78zi2OYNRKE7Nv6bkSN6oyKW9Rr7B29Eg4JfIk3RhbQhDUnkphUSzzv2CYWqVdyNDylWqfF7fniQHZuGeF/FiybCdO4oZDsoFiv/C4OF/d9ZTT6xP8clDjsQtjgkEQfnkCr63aR7GAbqRae6ZUIqH8vuJncWK7CpMwDEcUYniOOl+Dk2oqrFHEMBw6skTlWYL49GHglFAAA4UdxJVoJYs0teKOk85qg75F665I7mMy0fsT/ZL11SjpYoAd+Adnth7hG2gwkD6FdhCvE78oxFqsYFK3ipGJJk/OlmHaSJSGkhVPxXsmcXWXmOyTZEL9DrjBKWuRU1Oxu60BDBaFaFm4OphJzHusWzl1WfSFJmkYOvLgFh5/AEkJcwKGb57b0cNCHXEDFHD5txPqz24/3kPuvugIgpbjb2FgrtUp9Kj3CuXBYmQw1+cBiXZ+R0DxhtUDFnf0g+L/fGzDzNTVsiKs3KRV4acXXkqCiEXZXmPfB2MWk5fDM9WRepSLm82QMfbRj0YVKlH26KkbbuTsu,iv:S+QH8+T/tznJj+LFpKw38y7JKHMlr0+kNo3WwC8SO+c=,tag:pb8CEA6EkoRsGvqbADeq6Q==,type:str]
  1password-credentials.json: ENC[AES256_GCM,data:AVxileJ7Sp0h9+tx7olrRJa+uQCp6UQrFcWSR3TkJMr76ZXCxHcpKjxac4G9GbqnSImZbM8nJ0v6jdLEGCuAYVngYFJSuUYGlDIZ1YQMgRIQUyZHAqOcO6w4PSvDcBd9CX6UNC6ZilMr7x3B8DJaoQ3pwe2aye2fg33WrObuBKUAjsUZUyw40hDm21nHZJ0UD+D2KvybYf6udrUMDQJy5QdUb0ZyfvCyZOSGf+IiPNu7j+x9556ckNVd3CE2PP/PwrbG0Tmb7My5oPWd4tCG+ubv3d0AMdkXBuMeW0YG+TQKkUhTZ+k8lq8GnUZIl9iQtSf4nbFF3NxUI1+cADTt8n7HlLeOjyP7pilYpXlJO5bpBDZr8uS+4ktPhJEd4L/fRjQih72bO59ZhfGfXWWTPanjmC1IZX7azW1xg3dxdLaJR0ChJVxMcVpDJvET1W4D+dS1MoaQV5waxxwwFesUHBYAoLztUK0IaE3WCFXnU3ylxFHKf4lrYTi9lnqI3nxzKxT7URNzpaI4z9tsxu91/ij0dljgWtVJPngMM7lF47GuXVcj2Lyuz/MF/LpLZ6Ro6EnVv7LosOkxmanBwElOwy1p3d8UlAM3AnJJHQr3PMYw0nVjZcyHgXI4CVwg9KjhBMVxSNktCSPRUAfcOncKF4d+nQZpi8et7LiUkblU7CUln8wrKS0vdA6Gcra4f1xCnG2kHH/O3nhF3aQnOnB6Y9SxdqDFBRqflBzibF+5riYo7eJRlx7FTSzqSp2GbB7z7qrSgW6A7PtnzCyT9BqOz2xAPnxsSvwiIRXO/dKbwQGyarnWBQ6UVBqsz0zsWPG5sNhpAAAJK6ljHW+qN2IIWRNrm8dCUg5aZfWmNx+IbuCwWKfd/ER1pe8IMCgVddIjiAow55iXNjA3ruUga+nedUOlaDPPJ9FLqunXRyCk57OOkAsWYpk515Et32LS7PWEFYGZc4fYm2Od2gPTiIcNe0S2XSij5gRMe60GseXblQombc3DCL0MvBa3pfx9biLRA77FR2v2qCbgOWqO+eDluDg+CqwsE5GkgXQnViFWs+mGncn5OF8sMLW9BIL27FjUFe5Tyr8iqKeWEvyuvCdVMfztAh0JFv3yd78hkYsd/MZvLBL2/5Geb/H5q6OYMDQdLl2DyG/j3ulPsz1j4PtwyFC50IHJtewvs4sQiMCh8TBtzorx5tjqAacqS2h369rXi3aJSOnYog38AIG0M0EhqBQTXoyxrPnHdwwpReB/p0qNhZsPnLdDTt1tsIamx097d/Wtr9dPg0nr0WjFSwf5X3FecudEYdbhgBMJEf2GxQxuaYVqXZDyFljA0kIp3p9XXcjlrQm3xlMDNHJOeu0VOelTTeiSYR98NtVUuADtWUulAK5NBjuskyxi3avw6F5plya/gpUc9JdV7oy6Lw2fR3rk7AhZmXM3bpYsevGXnj07,iv:H3jw4S7TG5lh6BIlv2GxHJIU7sLUMmDesWb+q5Zkdx4=,tag:50HHWLA2c/j9T/pJjLu0sQ==,type:str]
sops:
  age:
    - recipient: age19r6wen3fypsw5ykk0dj2e2hc0tyw2zlux6mw33c57pfg5jd9mg9sgjp3za
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLWEt3VFdMZHdvdUY3aWNk
        ZXI3Vnd2OGF5cDY4UVNWZ091alFyM09wSkZrCi9jWWgzcUZOZnNjY1FVbktNNVNL
        NndCWjNMRVZrTmtHVkhST1M3ZkhTMlEKLS0tIDZGYWwzK1M4Um44aC9oM3lyb09z
        Rm5WT0dmRnR3SkdWVkk3N0l2THoxOWsK/F+BUkPCHEcOER1uvjDN8Kx0JnoMzAS1
        M1h7dUJ2dkWiC5wdo91BSL/WYqFDCSXA3JKO640fL7TDbKA4OXQxRA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-22T11:20:18Z"
  mac: ENC[AES256_GCM,data:MrJbeWZkzZTnuziQrk6R3NfR4IngS5Og3E546y0z1wFgLuoLbsq6sIeTCu7qkhitvaGJN+dabY89kKmzAR5dBg78Wchj2iK7S4MraKekspnXf884WVMi43DGfl1oUvq0pSxvairUaheo49GWu82BZLVjgMOZf6iD0ij3O25V4d8=,iv:lb1vIsNXW3BCsdClczgik8X+Xdjtxgv3kGZqI+l5tS8=,tag:yREK37C9LLvd5Pq6N4LkEw==,type:str]
  pgp:
    - created_at: "2026-03-22T11:27:42Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DAq0yvRRAWQ0SAQdAz9i50INkpwEdlgtn8JkinWCV6RcuUkUsxowAcImamzQw
        tx4Ij5r0Pbsfhk1K4zWbDUeT6N4n9p//ym6WZU0qvyEckY5bxaaIzjW1hZd4CLx6
        0l4BYnz7zgAG8Kwsaw3qRnFd2p6mS6t70aQAwtLD2VTlbsdR6C8G+CczSlDAjQz8
        Ny4aRi2AWxAxCBhQ+z2blcrRMc9obMm6YuXzP6dNtT4p1/FvwGe0d4UHpRUZ+Z9/
        =xAn5
        -----END PGP MESSAGE-----
      fp: 1818334CEAC35348ED5E30F5DD40CEDB2EEAD4A4
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
