# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app freecad
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      freecad:
        replicas: 1
        strategy: Recreate
        annotations:
          reloader.stakater.com/reload: "true"
        containers:
          app:
            image:
              repository: lscr.io/linuxserver/freecad
              tag: 1.0.1-ls86@sha256:13f83ba0b82aa7490924068d7e01e995d45846a9b3ded278a7107abf72c7d40e
            env:
              TZ: America/Los_Angeles
              PUID: "1000"
              PGID: "1000"
              DRINODE: /dev/dri/renderD128
            resources:
              requests:
                cpu: 100m
                memory: 128M
                amd.com/gpu: 1
              limits:
                cpu: 2000m
                memory: 4Gi
                amd.com/gpu: 1
    defaultPodOptions:
      nodeSelector:
        feature.node.kubernetes.io/custom-amd-gpu: "true"
    service:
      app:
        controller: freecad
        ports:
          http:
            port: &port 3000
    ingress:
      app:
        className: internal
        annotations:
          nginx.ingress.kubernetes.io/auth-url: "http://authelia.authelia.svc.cluster.local:9091/api/verify"
          nginx.ingress.kubernetes.io/auth-signin: "https://auth.${SECRET_DOMAIN}?rm=$request_method"
          nginx.ingress.kubernetes.io/auth-response-headers: "Remote-User,Remote-Name,Remote-Email,Remote-Groups"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            add_header Cache-Control "no-store";
            add_header Pragma "no-cache";
            add_header X-Frame-Options "SAMEORIGIN";
            add_header X-XSS-Protection "1; mode=block";
        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        enabled: true
        existingClaim: *app
        type: persistentVolumeClaim
        advancedMounts:
          freecad:
            app:
              - path: /config
      nas:
        enabled: true
        type: nfs
        server: ${CONFIG_NAS_IP_ADDRESS}
        path: "${CONFIG_NAS_DEFAULT_SHARE}/Apps/Freecad"
        advancedMounts:
          freecad:
            app:
              - path: /config/nas
