---
apiVersion: v1
kind: Endpoints
metadata:
  name: ldap
subsets:
  - addresses:
      - ip: ${CONFIG_NAS_IP_ADDRESS}
    ports:
      - name: ldap-389
        port: 389
        protocol: TCP
      - name: ldap-636
        port: 636
        protocol: TCP
