---
apiVersion: v1
kind: Endpoints
metadata:
  name: synology
subsets:
  - addresses:
      - ip: ${CONFIG_NAS_IP_ADDRESS}
    ports:
      - name: synology-5000
        port: 5000
        protocol: TCP
      - name: synology-5001
        port: 5001
        protocol: TCP
