apiVersion: v1
kind: Secret
metadata:
  name: ghcr-auth
  namespace: usjobs-staging
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:30Uaye/Xama6VjKECP847J+McvuPyBB4XInMD10NZJR9Fh823rNN+UF7k/P5sVtT5NfQA+uzl1dV1bArb2yOo4xwZCx9AKnzzDkQe16p88XCozXeTjO5OZ23j+m6vwfsWR3c9EC/,iv:nWvklkRFxSuRb2qy1ThNXDvM67mqcBX/VHdA55ZU/gI=,tag:p4sk9HjqRBpYznVBfPZpzg==,type:str]
sops:
  age:
    - recipient: age19r6wen3fypsw5ykk0dj2e2hc0tyw2zlux6mw33c57pfg5jd9mg9sgjp3za
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVXVNZ0ZLOTV2Vm1md3BN
        ZW1mdVo2SGJtYi9HeXA4MW5oZ29rTXhPdXo4Cm44L0lZQzBHTU5FdE1kTnRGcndI
        aGh1MGVKTXpYeEZSL0tyQU5jaDdWM1kKLS0tIERZQ2FyUWlFU1lSK2x0LzhTOUdq
        U2M2S3U4VFBocDUxeEhNM1N3V05zdFUKPMbXs9EwlTcZ2Xd+CG3zVA2g3uhLAAnU
        7h7MAgnO+ImPMqYNkb58WS1zzOLdzg3GqpYuCyqA0eZ4OEJ8czL3aQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T22:25:24Z"
  mac: ENC[AES256_GCM,data:8M//tcQCYrmuKulRKxbKCXLKyZKtzj0EerTTn9EIc1hN7mStARCNHIpcn080UJpih29dxWWRmxJk6ez8ntJaVKi8WWMKHWV1HTVEzZE5xSJ8GGCE0VQkD/iRJMuBcHMWWuHIA0dDGwva9543fheJv+65QuTQIEK+Vc3JpF8H+xU=,iv:xoiAjgB137MidD2zAfMjmPUQExOqfZP9bStZsgYRX20=,tag:RhTFS31yxpxdj+MCfFRb2Q==,type:str]
  pgp:
    - created_at: "2026-03-28T22:25:24Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DAq0yvRRAWQ0SAQdANp0bBd+PRk2u5wG75SSHM+bPZ9ffp0E+kK2AQoBReQ0w
        oRk4GpY6fKQJgJFIc42dCyazavHYtaHSnaxOLYj5g3l38BzCvSYqfC9Qw9MXeGML
        0lwBdPEFd8TJ6U3ZWbJRs0Ex6Scu6f7UmgH6jLNAQA0JhgH2TQ00ljviFeRWpOMQ
        MUo2YydHkwF5P/LIAnMmubx2V/2cPzzq4H1/NWQtg3mIG72wf0WYcLxA3uQtoA==
        =lCO8
        -----END PGP MESSAGE-----
      fp: 1818334CEAC35348ED5E30F5DD40CEDB2EEAD4A4
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
