apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:ffpinlD4ZnekCmC9ahA=,iv:6tPQ88vkds13VLU6/gx0dvYkRbK7Vgv69T4p+twWuik=,tag:ADDdzugh+1adzx9gjfjGqg==,type:str]
  H2WAY_DOMAIN: ENC[AES256_GCM,data:vOw2uFu4DOMmfGhz1CBK,iv:6P/dldfBYVIf970y26fSCzG1S3rNtIT/4FTnR4zAfmg=,tag:nBNnwNzAbBPx3t2iRcKYGA==,type:str]
sops:
  age:
    - recipient: age19r6wen3fypsw5ykk0dj2e2hc0tyw2zlux6mw33c57pfg5jd9mg9sgjp3za
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiYWZScFp6TzRLWDh1NkRV
        VEJPclhxZjBiRWtLVUNycXQ4Z05ienowTnlnClMxRUh1eVo0eTRmS29lWW9JYzZv
        SVdxaVdqVXBDR0dUZWIzaEwwOWtrT3cKLS0tIHRWQlBrZ2hKU01GZDd5OWNJQ0th
        R1ZBcHRFUjlNbGtBUU5FS2VqQlFWS0EKr/Hs7k9RUwCFsYRCWElDyv0n1zrM7bcx
        2H2pw2H7IE069uv8W2b2DCT1kcblddZ+tHLQ1EBUVAIpZRcrvdUBoQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T20:48:39Z"
  mac: ENC[AES256_GCM,data:ujFFdJe6hSIgFjNvixPL4Cvn0yHcjr4p1yWSVUDlcZR2Aq/Nr5o3E0d3FW8jfgGHY6ekj9acvl/mPVAdSe9ka/pdNodJV09yM6jl8A6gZSUNVIm2qvgPsnzTBP5HQtd/8AX6pZcVzFOBAiiEy/jONXE6pztFqNnPhYZqAFTSyiw=,iv:14LZpBpNQxZR0yvAL1G6vJb2ZSZZEFycr7OpYVZpOkk=,tag:tlIeLQdpY8EbXHz/s8tDsg==,type:str]
  pgp:
    - created_at: "2026-03-28T20:48:39Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DAq0yvRRAWQ0SAQdApSekQj6tFxBAHujYfnxDayf7L7pW8Fyrw24Dvmod+UMw
        kACQv6l+R5zKXX0ucXyri3ygHGQJCJpm3Of5wwH0n6RMW0A87gqH+IxXk6321hAz
        0l4BPLQUpTp9y6RwlMwDP/9pm+iov6QnTrlR1k/7ovKH4wKeVlX6uWC9YJpK7P7R
        CHjTljBDps52KdkaFIvOwuWxkVOjoG1ja58vQL/7EpChpRGzc4rdtEIG8ApmhXo1
        =Y0wm
        -----END PGP MESSAGE-----
      fp: 1818334CEAC35348ED5E30F5DD40CEDB2EEAD4A4
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
