apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-vars
data:
  CONFIG_OPNSENSE_IP_ADDRESS: 10.0.0.1
  CONFIG_NAS_IP_ADDRESS: 10.0.0.4
  CONFIG_NAS_DEFAULT_SHARE: "/volume1/Shared"
  CONFIG_NAS_k8s_SHARE: "/volume1/K8s"
  CONFIG_NAS_k8s_SUBDIR: "${pvc.metadata.namespace}/${pvc.metadata.name}"
