apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:scJtuAGX+P1IJcyVolw=,iv:/eET5kUz3ikekGJDwKinkFEFSQFk2oF+yG98UJ13T1U=,tag:yof2p0qOA4sO5xGYygalJA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnb3RaL0liUFRBN3JUQlBI
        dVBzaGtWamFhQWFkOVZERGtOQkttaEYybEFnCjFOVDVIMUE1SnloMzZWZGwxYW4v
        Nml2aEJKL3l1c2EveVRrbzlqQ2hQSlEKLS0tIEc3US81Y0xjdVBWZlpFZ3NzNEU3
        aDRDOE9LNWEwWHNNeG4wd01xQ2lrZlUK0zyoXAxIlmd8X3kLIiDsTfqZIHdO/kMm
        jnUlJdLcpnSCNUDyhe689E3eAFlSmcHPhrZ+sfbCkgVYmHh8tJHoBw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19r6wen3fypsw5ykk0dj2e2hc0tyw2zlux6mw33c57pfg5jd9mg9sgjp3za
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-19T06:35:27Z"
  mac: ENC[AES256_GCM,data:qgbLmDYrYFELQFWQu4lZD+Mh6WSrmksqqHJtWVCGtQnx8PzrvXhXReJ6/KtmEsdkAGn1PgD67u7/spQbN71jiW3i6MikJJ8QsbVJSZhZuGSHaD36OrwBDquI9HPgsU10Oz6Ev0uh1AzGHFJPapp9Cpxum0oA48/Hk+OYC/RBZLE=,iv:COteRhqhcs6R6Wime80M1T8L5wmfbp43/isywADOqpc=,tag:3H/Ws2aOcnLdEmzJ2SFrYg==,type:str]
  mac_only_encrypted: true
  pgp:
    - created_at: "2026-05-19T06:35:27Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DAq0yvRRAWQ0SAQdABSPCzjxXdA2W6jJkkCukxw3vTsOiH5hdLKmNqSg3IWow
        Rfg2mj9gPE1QanZNayeK+nPQ36KdtJ6Wkm/ZkEGwEQvySlEg1ym+NKT7ruBukgKS
        0l4Bitdsksqb3upgHa9WEQynbkg+r0iEdZKB1p9hc9UTZpmWqMbeV/M99YXHYqe1
        QDiYS5P6ElANz50YmfoQTPu2C8QKRlexqfknv4d/d7os8T/P2F+L1rTEqt/zFm2O
        =dK5L
        -----END PGP MESSAGE-----
      fp: 1818334CEAC35348ED5E30F5DD40CEDB2EEAD4A4
  version: 3.13.0
