apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:rcz7rQyDNx4Byl7ghws=,iv:R/aZB3jffVInbvTEyJal4VwBMUp0jGAuFseQCswmGSE=,tag:ga6ucjLNE0rgtS8YGE6Lkw==,type:str]
sops:
  age:
    - recipient: age19r6wen3fypsw5ykk0dj2e2hc0tyw2zlux6mw33c57pfg5jd9mg9sgjp3za
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZThNZWdUR0gycC81M2NY
        cXJUaHU4K2czWjR0Y2tRWmFONUJQeDdlU0RFCklrUXB2N2dlbk5pb3FSUnBjQVQ1
        RHBpRzhuQzRzV1hWSnlXbGN1Mnd4VGsKLS0tIDhpc3FkYUJseUxVSVZiczVpeHEr
        S1dWUEFqSzFDV0ZIek01VUxNTXo3WEEKnrp8MExSiZjJSodi3OVIdpiFI+y1a99m
        ugKkjyywsYR3HMLNLwRn1WFGSGUyReA45BiuFLuJCOIWXhJk33d+qw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-23T05:41:35Z"
  mac: ENC[AES256_GCM,data:xVHkBkDIrBC5XWsoRqlBLgVzxNplFzbbW0X6ugLUVj+z+TNhMyTazyObKna3fb6miBcBEjX3okS61KNe8EM/oRrOBZR47Q7EKJRdAXNUw6lIQhSIVnY8fySqweCzmxtkUzuO4oyBgSdhlOpIMzfa6Zo1VB6Jip48fbijmIKQuO0=,iv:Ts3z5XL3nmqNNnWNTOCm4/WWIB0KGIvM7as/ndDpzFU=,tag:uIx/Ec2nt6jg/YdRS37n3g==,type:str]
  pgp:
    - created_at: "2026-03-22T11:27:42Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DAq0yvRRAWQ0SAQdAmNYbGfs6yHlpRLsdSJOZHt0t+sxYUgx9ks/Z8OPhkwYw
        jL6etuF3b5IE67nXB56csPe1nB9bg9ZzrXBWQSfYnitR3f/QJBv9v8WqZa9gGV6N
        0l4B5nlzbBs7s3LW9WMSPLnCFiADuHY9b012cYVwS9hnSAu+IZ+qRI097WLQS5QS
        BiWhEgF8sP31WjGwp4994SzFJnfVKhf3hwlHJ+URziIziY4G/ehPCFSP1/kwATDk
        =hQOU
        -----END PGP MESSAGE-----
      fp: 1818334CEAC35348ED5E30F5DD40CEDB2EEAD4A4
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
