# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:K0BtIi8IhsRgfaFA3iRhiZ5nS+POMCGXlthn87wZB1bQC2PphZSH6w==,iv:R8DCYuzqGmbbA5THAG0qQ+Ly1ggMNHoCYbo457Jaags=,tag:fEMfDByPEEjCvJ71jI5F2g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19r6wen3fypsw5ykk0dj2e2hc0tyw2zlux6mw33c57pfg5jd9mg9sgjp3za
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3c2lYQ2pkaGVjRzFTTFBH
        TWRpYjlxRXhBenZRVFJwaWE2eER6NGpwaWxnCk8wWmZISTMzKzR1SHAzd1NkMnZw
        aDE1MlBrOXRxWDZNVkgzbkFQSGNFWEEKLS0tIFY1akhuL0dvbUlLaFZqbksvTmdi
        WHMrZmdzQVRkUVArbFNEek5KZ2FQNVUK336Mo6GiP+KU1yyom0gYjcCdsMdDqu+U
        CQnpaQh1D7QtZfFFTpCVje/Wosz8pK9kF+H1HiGIqfdhxrLrlqevEg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-23T05:41:35Z"
  mac: ENC[AES256_GCM,data:QI1FMqLSO6myfMsl7nZ2CkZ33xwNWRLRpsVp0Wf85kbamQOpZdNIPhIVqZZDsUiFBldW+CCtqgRth8zD7q0jNi9CXehGrXCreXyqP5tS57l3xU2d4r2YLCJpdgkomUOqcwq68pHcCU5KoSYZfzVCImyDE44NtNCeTG8+bP6G5/Y=,iv:+qXwqElJN0aiQymBbxzWU0S35868cR0vzGohHHFJTJ4=,tag:fxJqVqH1IPOTw8Awn8LsAA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
