---
# yaml-language-server: $schema=https://raw.githubusercontent.com/marcolongol/CRDs-catalog/refs/heads/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prefect-secret
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: prefect-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Prefect Server DB connection
        PREFECT_DB_HOST: &dbHost cloudnative-pg-rw.cloudnative-pg.svc.cluster.local
        PREFECT_DB_NAME: &dbName prefect
        PREFECT_DB_USER: &dbUser "{{ .POSTGRES_USER }}"
        PREFECT_DB_PASS: &dbPass "{{ .POSTGRES_PASSWORD }}"
        # Postgres init container
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASSWORD }}"
        INIT_POSTGRES_USER: *dbUser
  data:
    - secretKey: POSTGRES_SUPER_PASSWORD
      remoteRef:
        key: CLOUDNATIVE_PG
        property: POSTGRES_PASSWORD
  dataFrom:
    - extract:
        key: PREFECT