kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: openebs-replicated
allowVolumeExpansion: true
parameters:
  "protocol": "nvmf"
  "repl": "3"
  "fsType": "xfs"
  "thin": "true"
provisioner: io.openebs.csi-mayastor
