kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: openebs-single
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
allowVolumeExpansion: true
parameters:
  "protocol": "nvmf"
  "repl": "1"
  "fsType": "xfs"
  "thin": "true"
provisioner: io.openebs.csi-mayastor
