# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: think-cluster

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://10.0.10.200:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "10.0.10.200"
  - "think-cluster.marcolongo.dev"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "thinkctr01"
    ipAddress: "10.0.10.10"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/96f8c146a67c80daad900d3fc1a6976fe11062321eee9ab6ae2a6aea88b2d26e
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "6c:4b:90:70:dd:9b"
        dhcp: false
        addresses:
          - "10.0.10.10/23"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.0.10.1"
        mtu: 1500
        vip:
          ip: "10.0.10.200"
  - hostname: "thinkctr02"
    ipAddress: "10.0.10.20"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/96f8c146a67c80daad900d3fc1a6976fe11062321eee9ab6ae2a6aea88b2d26e
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "6c:4b:90:c5:da:ed"
        dhcp: false
        addresses:
          - "10.0.10.20/23"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.0.10.1"
        mtu: 1500
        vip:
          ip: "10.0.10.200"
  - hostname: "thinkctr03"
    ipAddress: "10.0.10.30"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/96f8c146a67c80daad900d3fc1a6976fe11062321eee9ab6ae2a6aea88b2d26e
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "6c:4b:90:cd:80:9a"
        dhcp: false
        addresses:
          - "10.0.10.30/23"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.0.10.1"
        mtu: 1500
        vip:
          ip: "10.0.10.200"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"
