---
# yaml-language-server: $schema=https://raw.githubusercontent.com/marcolongol/CRDs-catalog/refs/heads/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-secret
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: immich-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DB_URL: "postgresql://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASSWORD }}@cloudnative-pg-immich-rw.cloudnative-pg.svc.cluster.local:5432/immich"
        DB_USERNAME: "{{ .POSTGRES_USER }}"
        DB_PASSWORD: "{{ .POSTGRES_PASSWORD }}"
        DB_DATABASE_NAME: "immich"
        DB_HOSTNAME: "cloudnative-pg-immich-rw.cloudnative-pg.svc.cluster.local"
        JWT_SECRET: "{{ .JWT_SECRET }}"
        immich-config.json: |
          {
            "oauth": {
              "enabled": true,
              "autoRegister": true,
              "autoLaunch": true,
              "buttonText": "Login with Authelia",
              "issuerUrl": "https://auth.${SECRET_DOMAIN}/.well-known/openid-configuration",
              "clientId": "{{ .IMMICH_OIDC_CLIENT_ID }}",
              "clientSecret": "{{ .IMMICH_OIDC_CLIENT_SECRET }}",
              "scope": "openid email profile",
              "signingAlgorithm": "RS256",
              "profileSigningAlgorithm": "RS256",
              "storageLabelClaim": "preferred_username",
              "tokenEndpointAuthMethod": "client_secret_post"
            }
          }
  dataFrom:
    - extract:
        key: AUTHELIA
    - extract:
        key: IMMICH
