apiVersion: v1
kind: Secret
metadata:
  name: ghcr-auth
  namespace: flux-system
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:ncrl9HJwGpk9AVtSLjl6OGd6/wzfKV7gTYadk7+hURGzsC0BQ9Xap+RfKGSOma/F1zZQ/0f4j1+Deh/2oQ6m45UDgBmurDTjjmXV9j8zmCaW/1swNokxyYaHEQjrbAYfZUd0ePVs,iv:7kED/7H2BdRWQ1saYgrtDxa7U8NLgq2xbB9EDtBV0mA=,tag:M6jPQKVPTuWWqLwbhuf9Yw==,type:str]
sops:
  age:
    - recipient: age19r6wen3fypsw5ykk0dj2e2hc0tyw2zlux6mw33c57pfg5jd9mg9sgjp3za
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyeWNReGNaNDhzWlk3SVMr
        N09PaUlQdDJRd1JNNmNFS3FZcUF4QW9TSFF3Ck51clFqVGIrUWtLaGlRV204dURp
        a24xdTlhZW1TdnV1aTA2RWFCQXVMMHMKLS0tIDRrNzZHdWtYaHV4MlBabWkzT0Vv
        a2pMa0xkdi93aE1mdmJsZ0JTNHhUemsKMSwA3aVoLjLcN+jkRvyNO1jN7MCLkHiZ
        azr5jg9G3cyucyNrxPZZmHAmEOjX223XtNgY7W825SQj4jmHmQyXCA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T20:22:49Z"
  mac: ENC[AES256_GCM,data:KnD+woDEcf7S93GbnSL77rdnn9N1qaANrdxyiuu6NNVICIB+2pLmaYIx53utc73q37H5csJB7XGOerue4OV8n2Ne3SNe9hAkElOKlfpKkRzKI1gHYRnH/HF//jWvLdnxI7ffh6F7Y4WFgh0UZSlG73z5VRfdn2fXVL0rCcppLRs=,iv:bbZg+FfOSsD95STc7Zu/vrFEBM8X2mxGuowVuWRgEQw=,tag:9kgLB7NvTcRDcM303mVLkQ==,type:str]
  pgp:
    - created_at: "2026-03-28T20:22:49Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DAq0yvRRAWQ0SAQdAQL1YVdT3mbwopz46zkw3jyfUiS10ryv7wkpGdowMZk4w
        vV7oaWVOmoMrHWwLZKdLRd8JweXt1SWZO7+tB0hdbtFlHUTFymEkcRbQc1lf9O/f
        0l4BdZaoXJu90ieriVZ8tS1vB2n4s4a6oJCc18XdJhWWTAtzux/B0GoQNgbT3CeD
        8eclXv2gFV37XQDeIXz7S7O7lijSSnuUx8XXwpioj91tWCZZAHaTwzWPKzdcc9hB
        =HO5L
        -----END PGP MESSAGE-----
      fp: 1818334CEAC35348ED5E30F5DD40CEDB2EEAD4A4
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
