---
# yaml-language-server: $schema=https://raw.githubusercontent.com/marcolongol/CRDs-catalog/refs/heads/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-secret
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: paperless-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        PAPERLESS_SECRET_KEY: "{{ .PAPERLESS_SECRET_KEY }}"
        PAPERLESS_ADMIN_USER: "{{ .PAPERLESS_ADMIN_USER }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .PAPERLESS_ADMIN_PASSWORD }}"
        PAPERLESS_DBHOST: &dbHost cloudnative-pg-rw.cloudnative-pg.svc.cluster.local
        PAPERLESS_DBNAME: &dbName paperless
        PAPERLESS_DBUSER: &dbUser "{{ .POSTGRES_USER }}"
        PAPERLESS_DBPASS: &dbPass "{{ .POSTGRES_PASSWORD }}"
        # SECTION: POSTGRES
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASSWORD }}"
        INIT_POSTGRES_USER: *dbUser
  data:
    - secretKey: POSTGRES_SUPER_PASSWORD
      remoteRef:
        key: CLOUDNATIVE_PG
        property: POSTGRES_PASSWORD
  dataFrom:
    - extract:
        key: PAPERLESS
