kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: openebs-single
allowVolumeExpansion: true
parameters:
  "protocol": "nvmf"
  "repl": "1"
  "fsType": "xfs"
provisioner: io.openebs.csi-mayastor
