---
# yaml-language-server: $schema=https://raw.githubusercontent.com/marcolongol/CRDs-catalog/refs/heads/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: homepage-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        HOMEPAGE_VAR_GITEA_TOKEN: "{{ .GITEA_TOKEN }}"
        HOMEPAGE_VAR_PAPERLESS_TOKEN: "{{ .PAPERLESS_TOKEN }}"
        HOMEPAGE_VAR_GRAFANA_USER: admin
        HOMEPAGE_VAR_GRAFANA_PASS: "{{ .GRAFANA_ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: HOMEPAGE
    - extract:
        key: GRAFANA
