# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:iC87Q3t7tszO8Aj6h6oBq/W0eiuXNi3YCj+kkoIzozQ=,iv:mUpBlu2ObFhY3zyL3qipY0RVh5RXPqdIamGOhEbMk7Y=,tag:m0VEaVDg1lVMLG1bSum1kA==,type:str]
sops:
  age:
    - recipient: age19r6wen3fypsw5ykk0dj2e2hc0tyw2zlux6mw33c57pfg5jd9mg9sgjp3za
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyT3RqZGRjeDlQVGFlbHRi
        REtWdlpxNlZobHR6ckx6a3NYVGZ4YmtIUUVBClZaNis5NWFkV3FDSHNJSXpReWJS
        VGN3a3FZNVBGbitNQm9aWmo1VUFqSEEKLS0tIDliMHRteFhKRndhN0N3cFBTRjJ6
        UGkyN3BFL2hOb1o5aWd1L1RSSnB0eG8KpyB+qf0SmtudtRgcAxCiOv5NhyyKuHKM
        GPitjp6y+VuGqwzTnUWau3km5+xnzOireWLZASoVrrkE+0GxxqcU1w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-23T05:41:35Z"
  mac: ENC[AES256_GCM,data:THntoqI/iCOEobHqj772j+VUqU/QKf4dnhF6s2yywg/XdaOXrbmgw//eioBOj3YaW63sK6wze4R2eE/CFn5jbY4v3vEgiBmHrmaNNvSVwB6ib/wj7c7iWi9yccgcYF+y5x4AzR0LhkB0sn8Bi4ava+akj4gHTCkTPpSeoCBud5U=,iv:k2jqj9kn5wRGlc9+ba9Hd8UP/FOgOEyUogIl+n5QbKY=,tag:Zc6K3SGAXfKb4QN7UGXe9g==,type:str]
  pgp:
    - created_at: "2026-03-22T11:27:42Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DAq0yvRRAWQ0SAQdATbLGm+lLFbuCZoBck77gypVXMaa/61TFRupe+YOQBXYw
        63FcNZAcwXEsbhLKcLHs4wr8xecph2ufgMrpZfJoHpKyzi0eJA8ppMWIzIsmFHRx
        0lwBZHXke/6zx0Te6r8DGAv0532RbjcmOKEWBAfyAfmbYscL2EcksdRHpPYCRRJJ
        LxunPpnPMsSBRi7FxucJMWhZiso5hO0koG8CaChUtr46G1576DwGEwIYtJB2eQ==
        =1p31
        -----END PGP MESSAGE-----
      fp: 1818334CEAC35348ED5E30F5DD40CEDB2EEAD4A4
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
