---
# yaml-language-server: $schema=https://raw.githubusercontent.com/marcolongol/CRDs-catalog/refs/heads/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: vaultwarden-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # SECTION: VAULTWARDEN CONFIG
        ADMIN_TOKEN: "{{ .ADMIN_TOKEN }}"
        DATABASE_URL: "postgresql://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASSWORD }}@cloudnative-pg-rw.cloudnative-pg.svc.cluster.local:5432/vaultwarden"
        # SECTION: OIDC
        SSO_CLIENT_ID: "{{ .VAULTWARDEN_OIDC_CLIENT_ID }}"
        SSO_CLIENT_SECRET: "{{ .VAULTWARDEN_OIDC_CLIENT_SECRET }}"
        # SECTION: POSTGRES
        INIT_POSTGRES_DBNAME: &dbName vaultwarden
        INIT_POSTGRES_HOST: &dbHost cloudnative-pg-rw.cloudnative-pg.svc.cluster.local
        INIT_POSTGRES_PASS: &dbPass "{{ .POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASSWORD }}"
        INIT_POSTGRES_USER: &dbUser "{{ .POSTGRES_USER }}"
  data:
    - secretKey: POSTGRES_SUPER_PASSWORD
      remoteRef:
        key: CLOUDNATIVE_PG
        property: POSTGRES_PASSWORD
    - secretKey: VAULTWARDEN_OIDC_CLIENT_ID
      remoteRef:
        key: AUTHELIA
        property: VAULTWARDEN_OIDC_CLIENT_ID
    - secretKey: VAULTWARDEN_OIDC_CLIENT_SECRET
      remoteRef:
        key: AUTHELIA
        property: VAULTWARDEN_OIDC_CLIENT_SECRET
  dataFrom:
    - extract:
        key: VAULTWARDEN
