---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Renovate

on:
  push:
    branches: ["main"]
    paths:
      - .renovaterc.json5
      - .renovate/**.json5
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
    inputs:
      dryRun:
        description: Dry Run
        type: boolean
        default: false
        required: true
      logLevel:
        description: Log Level
        type: choice
        default: info
        options:
          - debug
          - info
        required: true
      version:
        description: Renovate Version
        default: latest
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  OP_CONNECT_HOST: ${{ secrets.OP_CONNECT_HOST }}
  OP_CONNECT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}

jobs:
  main:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - uses: 1password/load-secrets-action/configure@dafbe7cb03502b260e2b2893c753c352eee545bf # v3
        with:
          connect-host: ${{ env.OP_CONNECT_HOST }}
          connect-token: ${{ env.OP_CONNECT_TOKEN }}

      - uses: 1password/load-secrets-action@dafbe7cb03502b260e2b2893c753c352eee545bf # v3
        with:
          export-env: true
        env:
          BOT_APP_ID: op://homelab/GITHUB/GITHUB_APP_ID
          BOT_APP_PRIVATE_KEY: op://homelab/GITHUB/GITHUB_APP_PRIVATE_KEY

      - name: Generate Token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        id: app-token
        with:
          app-id: "${{ env.BOT_APP_ID }}"
          private-key: "${{ env.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Run Renovate
        uses: renovatebot/github-action@eb932558ad942cccfd8211cf535f17ff183a9f74 # v46.1.9
        env:
          LOG_LEVEL: "${{ inputs.logLevel || 'debug' }}"
          RENOVATE_AUTODISCOVER: true
          RENOVATE_AUTODISCOVER_FILTER: "${{ github.repository }}"
          RENOVATE_DRY_RUN: "${{ inputs.dryRun }}"
          RENOVATE_INTERNAL_CHECKS_FILTER: strict
          RENOVATE_PLATFORM: github
          RENOVATE_PLATFORM_COMMIT: true
        with:
          token: "${{ steps.app-token.outputs.token }}"
          renovate-version: "${{ inputs.version || 'latest' }}"
